name: Push Frontend Docker Image

on:
  push:
    branches:
      - main # main 브랜치에 변경사항이 생겼을 때 실행됨

  workflow_dispatch: # 수동 실행 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg REACT_APP_API_BASE_URL=${{ secrets.BASE_URL }} \
            --build-arg PROXY_API_BASE_URL=${{ secrets.PROXY_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_FRONTEND }} .

      - name: Push Frontend Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_FRONTEND }}

      - name: Execute Centralized Repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d '{"event_type": "frontend-update"}' \
            https://api.github.com/repos/GiSung-Song/task_manager_cicd/dispatches